HelloWorld/urls.py
from django.contrib import admin
from django.urls import include, path

from main.views.views import Home

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('main/', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path

from main.views import views
from main.views.memo.views import MemoListView, MemoUpdateView, MemoCreateView, MemoDeleteView

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),

    #  Memo Projects
    path('memos', MemoListView.as_view(), name='list_memo'),
    path('memos_edit/<int:pk>', MemoUpdateView.as_view(), name='edit_memo'),
    path('memos_new', MemoCreateView.as_view(), name='create_memo'),
    path('memos_delete/<int:pk>', MemoDeleteView.as_view(), name='delete_memo'),
]

main/models.py
from datetime import datetime

from django.db import models
from django.utils import timezone


# メモテーブル
class Memo(models.Model):
    class Meta:
        verbose_name = 'Memo Table'
        verbose_name_plural = 'Memos Table'
        db_table = 'memo'

    content = models.CharField(verbose_name='メモ', max_length=100, default='', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', default=timezone.now)

    def __str__(self):
        return str(self.id) + '(' + datetime(self.created_at).strftime('%Y/%m/%d %H:%M:%S') + ')'

main/forms/memo/forms.py
from django import forms

from main.models import Memo


class MemoForm(forms.ModelForm):
    class Meta:
        model = Memo
        fields = ['id', 'content', 'created_at']

    content = forms.CharField(
        label="Content",
        max_length=30,
        required=True,
        widget=forms.TextInput(attrs={'size': '30'}),
    )

    created_at = forms.DateField(
        label='Created at',
        required=False,
        input_formats=['%Y-%m-%d'],
        widget=forms.TextInput(attrs={'size': '12'}),
    )

main/views/memo/views.py
from datetime import datetime

from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse_lazy
from django.utils import timezone

from main.models import Memo
from main.forms.memo.forms import MemoForm


# メモ一覧画面
class MemoListView(generic.ListView):
    model = Memo
    queryset = Memo.objects.order_by('-created_at')
    # 1ページあたりの表示件数
    paginate_by = 10

    template_name = "main/memo/list_memo.html"
    success_url = reverse_lazy('home')


# メモ登録画面
class MemoCreateView(generic.CreateView):
    model = Memo
    form_class = MemoForm
    template_name = "main/memo/memo_form.html"
    success_url = reverse_lazy('main:list_memo')
    object = None

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.created_at = timezone.now()
        self.object.save()

        return redirect('main:list_memo')


# メモの更新画面
class MemoUpdateView(generic.UpdateView):
    model = Memo
    form_class = MemoForm
    template_name = "main/memo/memo_form.html"
    success_url = reverse_lazy('main:list_memo')
    object = None

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()

        return redirect('main:list_memo')


# メモの削除画面
class MemoDeleteView(generic.DeleteView):
    model = Memo
    success_url = reverse_lazy('main:list_memo')
    object = None

    def get(self, request, *args, **kwargs):
        self.object = Memo.objects.get(pk=kwargs['pk'])
        self.object.delete()
        return redirect('main:list_memo')

main/views/views.py
from django.shortcuts import render
from django.views import generic

from django.http import HttpResponse


def index(request):
    return HttpResponse("Tao Hello, world. You're at the main index!!!")


# 暫定ポータル画面へ移動
class Home(generic.TemplateView):
    template_name = 'main/home.html'

    def get(self, request, *args, **kwargs):
        context = super(Home, self).get_context_data()
        context.update({'my_message': 'Welcome to my site'})
        return render(request, 'main/home.html', context)

main/templates/main/base.html
{# Project: Hello World! #}

<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}{% endblock %}</title>

        {# --- css --- #}
        <meta http-equiv="Content-Style-Type" content="text/css">
        <style type="text/css">
            <!--
            body {
                padding-top: 5rem; #}
                {% block style_body_padding_top %}{% endblock %}
                padding-right:0;
                padding-left:0;
            }
            -->
        </style>
        {% block extra_css %}{% endblock %}
        <script language="javascript" type="text/javascript">
            <!--
            {% block extra_javascript %}{% endblock %}
            // -->
        </script>
    </head>

    <body>
    {% block header %}
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
            <h5 class="my-0 mr-md-auto font-weight-normal"><a href="{% url 'home' %}">Hello World</a></h5>
    </div>
    {% endblock %}

    <div class="container mt-3">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        {#  実装の中身 #}
        {% block content %}{% endblock %}

        {# ページネーション（定義のみ） #}
        {% block pagination_footer %}{% endblock %}
    </div>


    {# --- js --- #}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    {% block extra_js %}{% endblock %}
    </body>
</html>

main/templates/main/home.html
{# Project: MemoPad #}
{# HOME 画面 #}

{% extends "main/base.html" %}

{% block title %}Hello World!{% endblock %}

{% block content %}
    <br>
    <div class="container">

        <!-- Content -->
        <h3>Hello World!</h3>
        {{ my_message }}
        <br>
        <a id="memo_app" href="{% url 'main:list_memo' %}">メモの一覧</a>
    </div>
{% endblock %}

main/templates/main/memo/list_memo.html
{# Project: HelloWorld #}
{# Memo の 一覧画面 #}

{% extends "main/base.html" %}

{% block title %}List of Memo - Hello World!{% endblock title %}

{% block content %}
    <br>
    <div class="container">

        <!-- Content -->
        <h3>Listing of Memos</h3>

        {% if object_list|length == 0 %}
            <p>検索結果が存在しません。</p>
        {% else %}
            <table class="table table-striped table-bordered">
                <tr>
                    <th style="width:40%;">Memo</th>
                    <th style="width:30%;">日付</th>
                    <th>編 集</th>
                    <th>削 除</th>
                </tr>
                <tbody>
                {% for memo in object_list %}
                    <tr>
                        <td>{{ memo.content }}</td>
                        <td>{{ memo.created_at }}</td>
                        <td align="center">
                            <a id="edit_btn" href="{% url 'main:edit_memo' pk=memo.id %}">編集</a>
                        </td>
                        <td align="center">
                            <a id="delete_btn" href="{% url 'main:delete_memo' pk=memo.id %}">削除
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}

        <br>
        <a id="new_memo_link" href="{% url 'main:create_memo' %}">新規作成</a><br />

        <a id="home_link" href="{% url 'home' %}">Home へ戻る</a>
    </div>

{% endblock content %}

main/templates/main/memo/memo_form.html
{# Project: HelloWorld #}
{# Memo の 編集画面 #}

{% extends "main/base.html" %}

{% block title %}Editting Memo - Hello World!{% endblock %}

{% block content %}
    <br>
    <div class="container">
        <h4>メモの編集</h4>

        {% if form.errors and form.errors is not None and id != '0' %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-error">
                        <strong>・{{ field.label|escape }}：　{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-error">
                    <strong>・{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}

        <form action="" method="post">
            {% csrf_token %}
            <label>{{ form.content.label }}</label>{{ form.content }} <br />
            <input type="submit" value="保存" id="submit_btn">
        </form>

        <br>
        <a id="list_link" href="{% url 'main:list_memo' %}">一覧へ戻る</a>
    </div>
{% endblock %}